### ISSUE TITLE
Chapter 4 Question 6 (quiz)

### ISSUE THREAD

**Issue by mattmjohnson4** [GA-WDI/fundamentals#156]
Question 6 reads:

`` and `` tags need CSS to apply meaning to content.

It is a true or false question. I guessed false, and was rewarded with:

Not Quite
Not quite. Unlike the tags <p>, <h1>, and <a>, the <span> and <div> tags don't assign specific meaning to HTML elements without supporting CSS.

I'm not sure why I went with false, since every single true/false has always been the second option.

Question 13 told me I was correct, but when I hit continue it then went on to tell me that I was not correct, with the same explanation given. Based on my eventual score, my correct answer was obviously not counted.

**Comment by microsarah** [comment]
Fixed @jnappy

**Comment by jnappy** [comment]
@microsarah looks like question 6 is all good, but question 13 is still showing two answers: 

![image](https://cloud.githubusercontent.com/assets/7819607/18599793/38b31522-7c28-11e6-94bd-580780656490.png)

Can you take another look?

**Comment by microsarah** [comment]
Sorry for the delay @jnappy I didn't receive a notif for some reason. Working on this as soon as I get the typeform credentials.

**Comment by microsarah** [comment]
I saw an extra "wrong" answer for question 13 but didn't see any issues with the logic jump. I'm not great with typeform– can someone else take a look at this? @jnappy @jessicaGA

**Comment by jnappy** [comment]
this is logic within the typeform system - @jessicaGA and i looking into it

**Comment by jessicaGA** [comment]
The issue with the logic jump was resolved. @jnappy Can you verify and close this ticket?

**Comment by jnappy** [comment]
looks good!! closing
